# Generated by Django 3.2.9 on 2021-12-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_auto_20211130_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_api.useraccount'),
        ),
    ]
