# Generated by Django 3.2.9 on 2021-12-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_alter_project_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
